/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.samples.fbo.oidc.sid.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the OidcSid service. Represents a row in the &quot;OIDCSID_OidcSid&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.samples.fbo.oidc.sid.model.impl.OidcSidModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.samples.fbo.oidc.sid.model.impl.OidcSidImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OidcSid
 * @generated
 */
@ProviderType
public interface OidcSidModel
	extends BaseModel<OidcSid>, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a oidc sid model instance should use the {@link OidcSid} interface instead.
	 */

	/**
	 * Returns the primary key of this oidc sid.
	 *
	 * @return the primary key of this oidc sid
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this oidc sid.
	 *
	 * @param primaryKey the primary key of this oidc sid
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this oidc sid.
	 *
	 * @return the uuid of this oidc sid
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this oidc sid.
	 *
	 * @param uuid the uuid of this oidc sid
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the oidc sid ID of this oidc sid.
	 *
	 * @return the oidc sid ID of this oidc sid
	 */
	public long getOidcSidId();

	/**
	 * Sets the oidc sid ID of this oidc sid.
	 *
	 * @param OidcSidId the oidc sid ID of this oidc sid
	 */
	public void setOidcSidId(long OidcSidId);

	/**
	 * Returns the company ID of this oidc sid.
	 *
	 * @return the company ID of this oidc sid
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this oidc sid.
	 *
	 * @param companyId the company ID of this oidc sid
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this oidc sid.
	 *
	 * @return the user ID of this oidc sid
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this oidc sid.
	 *
	 * @param userId the user ID of this oidc sid
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this oidc sid.
	 *
	 * @return the user uuid of this oidc sid
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this oidc sid.
	 *
	 * @param userUuid the user uuid of this oidc sid
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this oidc sid.
	 *
	 * @return the user name of this oidc sid
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this oidc sid.
	 *
	 * @param userName the user name of this oidc sid
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this oidc sid.
	 *
	 * @return the create date of this oidc sid
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this oidc sid.
	 *
	 * @param createDate the create date of this oidc sid
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this oidc sid.
	 *
	 * @return the modified date of this oidc sid
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this oidc sid.
	 *
	 * @param modifiedDate the modified date of this oidc sid
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the session ID of this oidc sid.
	 *
	 * @return the session ID of this oidc sid
	 */
	@AutoEscape
	public String getSessionId();

	/**
	 * Sets the session ID of this oidc sid.
	 *
	 * @param sessionId the session ID of this oidc sid
	 */
	public void setSessionId(String sessionId);

	/**
	 * Returns the sid of this oidc sid.
	 *
	 * @return the sid of this oidc sid
	 */
	@AutoEscape
	public String getSid();

	/**
	 * Sets the sid of this oidc sid.
	 *
	 * @param sid the sid of this oidc sid
	 */
	public void setSid(String sid);

	/**
	 * Returns the jwks uri of this oidc sid.
	 *
	 * @return the jwks uri of this oidc sid
	 */
	@AutoEscape
	public String getJwksUri();

	/**
	 * Sets the jwks uri of this oidc sid.
	 *
	 * @param jwksUri the jwks uri of this oidc sid
	 */
	public void setJwksUri(String jwksUri);

	/**
	 * Returns the issuer of this oidc sid.
	 *
	 * @return the issuer of this oidc sid
	 */
	@AutoEscape
	public String getIssuer();

	/**
	 * Sets the issuer of this oidc sid.
	 *
	 * @param issuer the issuer of this oidc sid
	 */
	public void setIssuer(String issuer);

	/**
	 * Returns the alg of this oidc sid.
	 *
	 * @return the alg of this oidc sid
	 */
	@AutoEscape
	public String getAlg();

	/**
	 * Sets the alg of this oidc sid.
	 *
	 * @param alg the alg of this oidc sid
	 */
	public void setAlg(String alg);

	/**
	 * Returns the status of this oidc sid.
	 *
	 * @return the status of this oidc sid
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this oidc sid is status.
	 *
	 * @return <code>true</code> if this oidc sid is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this oidc sid is status.
	 *
	 * @param status the status of this oidc sid
	 */
	public void setStatus(boolean status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(OidcSid oidcSid);

	@Override
	public int hashCode();

	@Override
	public CacheModel<OidcSid> toCacheModel();

	@Override
	public OidcSid toEscapedModel();

	@Override
	public OidcSid toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}